spring:
  application:
    name: backend

server:
  port: 8080

logging:
  level:
    net.likelion: DEBUG

springdoc:
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs

jwt:
  secret: this-is-very-long-secret-ket-for-likelion-14th-session-test
  expiration: 86400000