spring:
  application:
    name: backend

server:
  port: 8080

logging:
  level:
    net.likelion: DEBUG

springdoc:
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs